### ISSUE TITLE
odoo 8 : export accounts list to import it into odoo 10 or 11

### ISSUE THREAD

**Issue by yboujraf** [Yenthe666/Odoo_Samples#10]
Dear,

I am looking to migrate from odoo 8 to odoo 10 or 11 community version.

I tried to export my accounts list and products but there are too many fields are linked with other tables.

Do you have any idea if a script is available to do that ?

Best Regards
Youssef

**Comment by Yenthe666** [comment]
Hi @yboujraf,

Not really. Manual export/import or creating your own scripts to move data or official Odoo upgrades I guess.

Regards,
Yenthe
