### ISSUE TITLE
ERPpeek AccessDenied

### ISSUE THREAD

**Issue by warrag** [Yenthe666/Odoo_Samples#14]
Hello every one 

When I am using this lib I got `xmlrpc.client.Fault: <Fault AccessDenied: 'Access denied'>` 

@Yenthe666  please any help with this 

best regards

**Comment by Yenthe666** [comment]
Show an example of the code please :)

**Comment by warrag** [comment]
@Yenthe666  this is the code 

`def write(self, values):

        DATABASE = 'db_name'
        SERVER = self.env["ir.config_parameter"].get_param("server")
        ADMIN_PASSWORD = self.randomStringDigits()

        client = erppeek.Client(server=SERVER)

        if not DATABASE in client.db.list():
            print("The database does not exist yet, creating one!")
            client.create_database(ADMIN_PASSWORD, DATABASE)
        else:
            print("The database " + DATABASE + " already exists.")
        
        res = super(SaleOrder, self).write(values)
        return res`


this issue it's come in `client.create_database(ADMIN_PASSWORD, DATABASE)`

**Comment by Yenthe666** [comment]
I might be missing something but I think you've set a master password which you're not setting in the script?

**Comment by warrag** [comment]
Thanks a lot it's work now

**Comment by Yenthe666** [comment]
Awesome, have fun :)

**Comment by warrag** [comment]
@Yenthe666 Hello again 
what is this error?

`xmlrpc.client.Fault: <Fault warning -- One or more of the selected modules have already been uninstalled, if you believe this to be an error, you may try again later or contact support.: ''>`

**Comment by yenykm** [comment]
Had the same problem ... you guys saved my night. Thanks a lot.

**Comment by Krishna-Sharma-BSI** [comment]
hi @Yenthe666 @warrag  @yenykm  I am having same issue in version 15.0 while trying to access through python script
in odoo.conf admin_passwd is admin 
I have use same
        DATABASE = db_name
        SERVER = 'http://localhost:8069'
        ADMIN_PASSWORD = 'admin'
        client = erppeek.Client(server=SERVER)
        client.create_database(ADMIN_PASSWORD,DATABASE)
        but getting issue, can someone guide me please ?

**Comment by Krishna-Sharma-BSI** [comment]
@all
