### ISSUE TITLE
Uninstall modules Exception

### ISSUE THREAD

**Issue by warrag** [Yenthe666/Odoo_Samples#15]
Hello @Yenthe666 

when I uninstall modules from server this Exception comes

`<Fault warning -- One or more of the selected modules have already been uninstalled, if you believe this to be an error, you may try again later or contact support.: ''> `

and this my code:
`
 modules = client.modules('enterprise', installed=True)
                if 'web_enterprise' in modules['installed']:
                    for m in modules['installed']:
                         client.uninstall(str(m))
`

any solutions

**Comment by Yenthe666** [comment]
Well one of the subdependencies of a module you've triggered to be uninstalled is probably uninstalled before your loop accesses it.
E.g:
module "X" is triggered to be uninstalled by your script and dependency "Y" is uninstalled. Your loop then accesses "Y" and tries to uninstall while it is already uninstalled. Out of scope of my samples ;)
